Update EventGrid SDK to T2
Azure-Samples/event-grid-dotnet-handle-deadlettered-events pull request #4
Opened 2021-12-09 02:59 UTC by v-yilinhu

1. Update EventGrid SDK to T2

2. Update files:

    - ./function-app/ProcessDeadLetterFunction.cs
    - ./function-app/WebhookSubscriptionFunction.cs
    - ./function-app/function-app.csproj

2021-12-09 16:44 UTC, scottaddie requested changes

2021-12-20 06:11 UTC, v-xuto commented
@scottaddie We have updated by your comments, please re-review this PR.

2022-02-11 09:52 UTC, v-xuto commented
@scottaddie We have updated by your comments, please re-review this PR.

2022-02-25 08:47 UTC, v-xuto commented
@scottaddie, @AlexGhiondea, @jameszliao-msft, @ellismg and @ahamad-MS Could you please review this PR?

2022-02-25 19:29 UTC, ellismg reviewed
I had a question for @JoshLove-msft about the trigger signature.

2022-02-25 19:29 UTC, ellismg commented on function-app/ProcessDeadLetterFunction.cs
> +        public static void Run([EventGridTrigger]JObject eventGridEvent, ILogger logger)
Sort of surprised to see the trigger binding against JObject here, instead of EventGridEvent.  @JoshLove-msft, is this the recommended way to do this with the new extension?

2022-02-27 20:50 UTC, JoshLove-msft commented on function-app/ProcessDeadLetterFunction.cs
> +        public static void Run([EventGridTrigger]JObject eventGridEvent, ILogger logger)
Both the old extension and new extension have JObject binding support. Looking at the usage, I don't see any reason to bind to JObject, and would suggest binding to EventGridEvent.

2022-02-27 20:50 UTC, JoshLove-msft commented on function-app/ProcessDeadLetterFunction.cs
> +            JObject dataObject = egEvent.Data.ToObjectFromJson<JObject>();
No need to convert to JObject here and I'm pretty sure this won't actually work.

2022-02-27 20:51 UTC, JoshLove-msft commented on function-app/WebhookSubscriptionFunction.cs
> +                JObject dataObject = eventGridEvent.Data.ToObjectFromJson<JObject>();
This can be removed and you can call ToObjectFromJson on line 40 on eventGridEvent.Data.

2022-02-27 20:52 UTC, JoshLove-msft commented on function-app/function-app.csproj
> +		<PackageReference Include="Azure.Messaging.EventGrid" Version="4.7.0" />
```suggestion
		<PackageReference Include="Azure.Messaging.EventGrid" Version="4.8.2" />
```

2022-02-27 20:52 UTC, JoshLove-msft commented on function-app/function-app.csproj
> +		<PackageReference Include="Azure.Messaging.EventGrid" Version="4.7.0" />
This isn't needed as the relevant dependency will be pulled in via the extension reference.

2022-02-27 20:52 UTC, JoshLove-msft commented on function-app/function-app.csproj
> +		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="3.0.0" />
```suggestion
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="3.1.0" />
```

2022-03-01 08:16 UTC, v-yilinhu commented
@JoshLove-msft I have updated, please review.

2022-03-15 09:12 UTC, v-xuto commented
@JoshLove-msft We have updated by your comments, please re-review this PR. Thanks a lot.

2022-04-01 08:30 UTC, v-xuto commented
@JoshLove-msft We have updated by your comments, please re-review this PR. Thanks a lot.

2022-04-01 17:56 UTC, JoshLove-msft approved these changes

2022-04-02 02:00 UTC, v-xuto commented
@jongio Please help merge this PR.

2022-04-04 03:36 UTC, merged